name: flutter_m8
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  image_picker: ^0.7.4
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  http: ^0.13.3
  clipboard: ^0.1.3
  url_launcher: ^6.0.12
  fluttertoast: ^8.0.8
  currency_text_input_formatter: ^2.1.5
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.2.0

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/xml/